import type { Metadata } from "next";
import Layout from "@/layout/layout";
import { myFont } from "@/utils/fonts";
import Provider from "@/providers/Provider";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootProps>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={myFont.className}>
        <Provider>
          
          <Layout>{children}</Layout>
        </Provider>
      </body>
    </html>
  );
}
